name = "MPSKitLEMPO"
uuid = "def4d40e-06d3-41a1-a405-61dcef04a768"
authors = ["Benjamin SÃ¸gaard"]
version = "0.1.0"

[deps]
BlockTensorKit = "5f87ffc2-9cf1-4a46-8172-465d160bd8cd"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MPSKit = "bb1c41ca-d63c-52ed-829e-0820dda26502"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BlockTensorKit = "0.3.1"
Documenter = "1.16.1"
MPSKit = "0.13.8"
MPSKitModels = "0.4.4"
OhMyThreads = "0.8.3"
TensorKit = "0.15.3"
Test = "1.11.0"
